### ISSUE TITLE
Move conf.py to be the popconf system

### ISSUE THREAD

**Issue by thatch45** [saltstack/pop#33]
The conf.py file is only being used to house configuration data. I am leaning towards changing it to be yaml/toml/json and adding to the standard setup.py file to compile it to msgpack.

**Comment by thatch45** [comment]
We could also add a config that states what the first subsystem to load is, that way the startup script could be dynamic.
It could also hold the version number...

**Comment by thatch45** [comment]
So it would look like this in YAML (assuming we used yaml):

```
CONFIG:
  foo:
    default: bar
    help: Some foo
VERSION: 6.0.0
SPINE: poppy  #so it would load the poppy sub in the script that would be generated by the setup.py
DYNE:
  - poppy
  - grains
```
